### ISSUE TITLE
Doesnt work / php.ini modification missing

### ISSUE THREAD

**Issue by philicious** [neiltheblue/ssmtp-wordpress#1]
Mailing from Wordpress, like "forgot password" doesnt work as is. You seem to be missing 
`echo 'sendmail_path = "/usr/sbin/ssmtp -t"' > /usr/local/etc/php/conf.d/mail.ini` in your Dockerfile/entrypoint

Refer to https://github.com/docker-library/php/issues/135 and https://github.com/docker-library/wordpress/issues/30

**Comment by neiltheblue** [comment]
Thank you, I have added this to prep_ssmtp.sh.
